### ISSUE TITLE
License changed to BSD, but files headers point to GPL

### ISSUE THREAD

**Issue by agarie** [SciRuby/distribution#1]
(Original: [clbustos/distribution#15](https://github.com/clbustos/distribution/issues/15))

Hi,

With commit 6a7d8c0, the license changed to BSD-3-clause, but some file headers (I think only lib/distribution.rb) still points to the GPL-2+. You should remove them.

Thanks,

Cédric

**Comment by vaibhav-y** [comment]
Here's my thoughts on this:

* `grep -r -l GNU .` returns: `./lib/distribution.rb`
* `grep -r -l [cC]opyright  .` returns:
```bash
./LICENCE.md
./lib/distribution.rb
./.git/hooks/pre-rebase.sample
```
* `grep -r -l [fF]ree\ [sS]oftware\ [fF]oundation . ` returns `./lib/distribution.rb`

I think its reasonable enough to believe that `lib/distribution.rb` is the only one.

Will create a PR for this soon

**Comment by envp** [comment]
- `grep -r -l GNU .` returns: `./lib/distribution.rb`
- `grep -r -l [cC]opyright  .` returns:

``` bash
./LICENCE.md
./lib/distribution.rb
./.git/hooks/pre-rebase.sample
```
- `grep -r -l [fF]ree\ [sS]oftware\ [fF]oundation .` returns `./lib/distribution.rb`

I think its reasonable enough to believe that `lib/distribution.rb` is the only one.

Edit: @agarie @clbustos this can be closed now, thanks!
