### ISSUE TITLE
Create a Distribution::Uniform

### ISSUE THREAD

**Issue by agarie** [SciRuby/distribution#22]
We have Ruby's `Random` class that can be used for this. The main point isn't implementing a new uniform RNG, but having a single interface for all distributions supported. This way, someone won't have to use two different APIs when he's working with normal (e.g.) and uniform random numbers.

**Comment by vaibhav-y** [comment]
But can we wrap ruby's `Random` through `Distribution::Uniform` to provide the `cdf`, `pdf`, `p_value` and `rng` methods?

**Comment by envp** [comment]
I'd be happy to take part in this, can you tell me how to start?

I'm browsing the other distributions to understand the structure for this. Would appreciate some help on proper environment setup / linting to be used, required reading etc.
