### ISSUE TITLE
Complete the table of methods availability

### ISSUE THREAD

**Issue by agarie** [SciRuby/distribution#24]
I wrote a table to track the methods available for each distribution, at least until most of them are implemented. It is in the [README](https://github.com/SciRuby/distribution#distribution).

The problem is that it is incomplete right now. I marked most methods as unavailable, but we need to check what is available and what isn't. Also, there should be some code to know if a method is available in pure Ruby or by using the GSL/Java bindings. Not sure if that is necessary, tho.

Related to #12 and #19.

**Comment by envp** [comment]
#30 fixes this. Will make sure that future updates also update the README's table of methods.

Closing issue
