### ISSUE TITLE
Seed in Normal RNG

### ISSUE THREAD

**Issue by agisga** [SciRuby/distribution#26]
I was trying to generate random number from the Normal distribution supplying a seed for reproducibility, when I looked at the [code](https://github.com/sciruby/distribution/blob/master/lib/distribution/normal/ruby.rb#L14) and noticed:

``` Ruby
        # Return a proc which return a random number within a
        # gaussian distribution X ~ N(+mean+,+sigma+^2)
        # +seed+ feed the
        # == Reference:
        # * http://www.taygeta.com/random/gaussian.html
        def rng(mean = 0, sigma = 1, _seed = nil)
```

(1) `_seed` can be supplied but is _never used_.

(2) Additionally, the comment/documentation is bad. The line "+seed+ feed the" makes no sense. And I don't think that one can say "random number within a distribution", it should rather be "number randomly drawn from the gaussian distribution" or something similar.

**Comment by agarie** [comment]
> Additionally, the comment/documentation is bad.

A more precise way of saying that is _the documentation is awful_. ;)

You are correct, that phrasing is wrong. I'll work on this issue tomorrow afternoon; I have a very urgent deadline tomorrow morning. I'll gladly accept a pull request fixing this if you have the time!

By the way, the normal RNG is using the default [Random class](http://ruby-doc.org/core-2.2.0/Random.html#method-i-rand) in Ruby, so it shouldn't be too hard to use the seed.

**Comment by agisga** [comment]
Yes, it looks like an easy fix. I will work on it today.
